### ISSUE TITLE
Crash trying to get an Item's `name`

### ISSUE THREAD

**Issue by zethon** [zethon/ttvg#23]
On macOS, I load up the game and walk immediately to the left near the sax. Once I get close to it I see a crash here:

![image](https://user-images.githubusercontent.com/5203583/88542850-1a10f200-cfe5-11ea-9e9d-42eeb210dd27.png)

The call stack is: 

```
__cxa_throw (@__cxa_throw:3)
nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer>::operator[](unsigned long) const (/Users/maxpower/.conan/data/jsonformoderncpp/3.4.0/vthiery/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/nlohmann/json.hpp:3157)
tt::Item::getName() const (/Users/maxpower/src/ttvg/src/Item.cpp:32)
tt::Opening::timestep()::$_3::operator()(std::__1::shared_ptr<tt::Item>) const (/Users/maxpower/src/ttvg/src/Scenes/Opening.cpp:335)
tt::Opening::timestep()::$_3 std::__1::for_each<std::__1::__wrap_iter<std::__1::shared_ptr<tt::Item>*>, tt::Opening::timestep()::$_3>(std::__1::__wrap_iter<std::__1::shared_ptr<tt::Item>*>, std::__1::__wrap_iter<std::__1::shared_ptr<tt::Item>*>, tt::Opening::timestep()::$_3) (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:859)
tt::Opening::timestep() (/Users/maxpower/src/ttvg/src/Scenes/Opening.cpp:329)
tt::GameScreen::timestep() (/Users/maxpower/src/ttvg/src/GameScreen.cpp:29)
tt::TooterEngine::timestep() (/Users/maxpower/src/ttvg/src/Engine.cpp:33)
main (/Users/maxpower/src/ttvg/src/main.cpp:104)
start (@start:4)
start (@start:4)
```

I haven't seen this on my Windows machine.

Also, this is the same crash I saw a few days ago.

I'll keep looking at it, but I wanted to create an issue so we don't forget about it.

**Comment by zethon** [comment]
I think this is probably related to the copying of the JSON object. I found this comment that's from 2017, but maybe it still applies:

https://github.com/json-c/json-c/issues/301

> There is currently no copy function available, but it could be implemented with json_c_visit. A pull request to add this would be welcome.

**Comment by zethon** [comment]
Changing the JSON getter functions like below fixed the problem (note: I had to do it on every function using the `_json` object):

```
    std::string Item::getName() const
    {

        //
        // Why is it that the json object can be treated as a top level
        // associative array when this is created in ItemFactory but 
        // after it is assigned to the member variable in this object
        // instance, it becomes a json array at the top level, 
        // and we must use _json[0] to get the first item?
        //
        return _json["name"];
    }

    std::string Item::getDescription() const
    {
        return _json["description"];
    }

    bool Item::isObtainable() const
    {
        if(_json[0].find("obtainable") == _json[0].end())
        {
            return false;
        }
        return _json["obtainable"];
    }
```

**Comment by charmyt** [comment]
On Ubuntu anyway, the json can be accessed in this way when it is created in the ItemFactory. The json object looks like "{...}".  But after it is assigned to the json member in the Item itself, it turns into "[{...}]".

Hence that long comment I had asking why this is.

I notice in Background.h you have the private member as 
    std::unique_ptr<nl::json>   _json;
In Item.h this is:
            nl::json    _json;

You also have different usage in the Background.cpp constructor to read the file into the _json member. Maybe this is where I went wrong.

**Comment by charmyt** [comment]
You'll also want to change this.

```
        if(_json[0].find("obtainable") == _json[0].end())
```
